language: go
go:
  - "1.14"
sudo: false
script:
  - go install -v ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)
